---

resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource

resources:
- name: source-code
  type: git-multibranch
  source:
    uri: https://github.com/orsond/demo
    branches: '.*'
    ignore_branches: 'master'


jobs:
- name: initialize
  serial: true
  plan:
    - get: source-code
      trigger: true
    - task: get-git
      file: get/ci/get-git.yml
    - put: source-code


