---

task-config: &task-config
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: maven
      tag: '3.6.1-jdk-8-slim'
  inputs:
  - name: source-code
  outputs:
  - name: source-code

resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource

resources:
- name: source-code
  type: git-multibranch
  source:
    uri: https://github.com/orsond/demo
    branches: '.*'
    ignore_branches: 'master'


jobs:
- name: build
  serial: true
  plan:
    - get: source-code
      trigger: true
    - task: build-local
      config:
      
        << : *task-config
        run:
          path: sh
          args:
          - -exc
          - |
            cd source-code
            mvn test
- name: initialize
  serial: true
  plan:
    - get: source-code
      trigger: true
      passed: [build]
    - task: get-git
      file: source-code/ci/get-git.yml
      



